files:
  - source: '/src/main/resources/de/theit/jenkins/crowd/**/*.properties'
    translation: '/src/main/resources/de/theit/jenkins/crowd/**/%file_name%_%two_letters_code%.properties'
    escape_quotes: 0
    escape_special_characters: 0
  - source: '/src/main/resources/de/theit/jenkins/crowd/**/*.html'
    translation: '/src/main/resources/de/theit/jenkins/crowd/**/%file_name%_%two_letters_code%.html'
    escape_quotes: 0
    escape_special_characters: 0

project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
