---
version: '3.8'
services:
  jenkins:
    build:
      context: ../
      dockerfile: casc/Dockerfile
      args:
       - JENKINS_SITE_NAME=${JENKINS_SITE_NAME}
       - JAVA_VERSION=${JAVA_VERSION}
    privileged: true
    user: root
    ports:
     - 8080:8080
     - 50000:50000
    container_name: jenkins
    networks:
      - crowd_net
    restart: always

    volumes:
     - jenkins_home:/var/jenkins_home
     - /var/run/docker.sock:/var/run/docker.sock

  crowd:
    image: atlassian/crowd:5.1.5-jdk11
    container_name: crowd
    networks:
      - crowd_net
    volumes:
      - crowd_home:/var/atlassian/crowd
    ports:
      - '8095:8095'

volumes:
  crowd_home:
    external: false
  jenkins_home:
    external: false

networks:
  crowd_net:
    driver: bridge
